# Generated by Django 3.2.6 on 2021-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='interesting_url',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=2500)),
                ('salary', models.IntegerField()),
                ('datePosted', models.TextField(max_length=50)),
                ('validThrough', models.TextField(max_length=50)),
                ('hiringOrganization', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=50)),
                ('place', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='non_interesting_url',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
