# Generated by Django 3.2.6 on 2021-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='syn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobdb',
            name='salary',
            field=models.TextField(max_length=50),
        ),
    ]
